### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Dan-Lt** [nanoporetech/ont_tutorial_pinfish#11]
While trying to run the tutorial with my own data I got this error which I don't understand, I also got a warning "Best cuttoff value is at the edge of the search interval! Using tuned value is not safe! Please pick a q value manually and QC your data!" and I got a low % of passing quality filters (Q >= 7.0).

![Screenshot from 2020-05-26 17-18-01](https://user-images.githubusercontent.com/58937429/82915261-2f33bb00-9f79-11ea-9719-29995ddc5a60.png)

[config.zip](https://github.com/nanoporetech/ont_tutorial_pinfish/files/4682991/config.zip)

**Comment by sagrudd** [comment]
Hello @Dan-Lt - this is indeed a strange error message; the mysteries of go executables!
The pinfish software that this workflow is based on is being retired in preference of two new isoform detection pipelines - one reference based https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms and one de novo based - https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms.
I would strongly recommend that you have a look at these pipelines as successors to pinfish and request that you have a look at the updated and now supported tutorials in EPI2ME Labs (https://labs.epi2me.io)
