### ISSUE TITLE
runtime error while running snakemake with my own data

### ISSUE THREAD

**Issue by Dan-Lt** [nanoporetech/ont_tutorial_pinfish#12]
got the error: " panic: runtime error: invalid memory address or nil pointer dereference "

I also got the warning message "Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index." which I don't understand.
I'v added the config file and the screen images.

![Screenshot from 2020-05-27 14-23-06](https://user-images.githubusercontent.com/58937429/83013511-d110e180-a025-11ea-9122-56580a0be3da.png)
![Screenshot from 2020-05-27 14-23-14](https://user-images.githubusercontent.com/58937429/83013522-d66e2c00-a025-11ea-9ba6-7b200917f0ef.png)
![Screenshot from 2020-05-27 14-23-22](https://user-images.githubusercontent.com/58937429/83013536-da9a4980-a025-11ea-9e8b-bf1f58dab452.png)
![Screenshot from 2020-05-27 14-23-25](https://user-images.githubusercontent.com/58937429/83013554-e0902a80-a025-11ea-81ce-8f7c9869b5c7.png)
[config.zip](https://github.com/nanoporetech/ont_tutorial_pinfish/files/4688402/config.zip)

**Comment by sagrudd** [comment]
Hello @Dan-Lt - this is indeed a strange error message; the mysteries of go executables!
The pinfish software that this workflow is based on is being retired in preference of two new isoform detection pipelines - one reference based https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms and one de novo based - https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms.
I would strongly recommend that you have a look at these pipelines as successors to pinfish and request that you have a look at the updated and now supported tutorials in EPI2ME Labs (https://labs.epi2me.io)
